console.log("----------------------------------------------------------");
console.log("|             Como realizar un console.log 😊            |");
console.log("----------------------------------------------------------");
console.log("");
console.log('1) Abrir un editor de codigo (Como puede ser "VisualStudio Code")');
console.log("2) Crear una carpeta en algun lado de la computadora (Un espacio de trabajo)");
console.log("3) Copiar la direccion del espacio de trabajo en el lado superior de la carpeta");
console.log("4) Volver al VisualStudio Code y apretar en el apartado de File");
console.log('5) Apreta la opcion llamada "Open Fonder"');
console.log("6) En el buscador de carpetas pegá la direccion copiada anteriormente");
console.log('7) Apreta el botón "Abrir"');
console.log('9) Una vez dentro, crea un archivo por ejemplo "holaMundo.js" o "holaMundo.ts" en caso de usar typescript');
console.log('10) Escribe una linea de codigo que diga "console.log()"');
console.log("(Esta puede llamar variables, puede marcár un texto o verificar booleanos entre otras cosas...)");
console.log('11) En caso de querer añadir un texto en las logs de la consola, agrega por ejemplo entre comillas, "HolaMundo"');
console.log('Y quedaria algo así: console.log("Hola Mundo") ');
